apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APP
  name: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  selector:
    matchLabels:
      app: APP
  replicas: 1
  template:
    metadata:
      labels:
        app: APP
    spec:
      containers:
        - name: APP
          image: ImageName
          ports:
            - containerPort: PORT
          imagePullPolicy: IfNotPresent
        #           env:
        #            - name: TZ
        #              value: Africa/Nairobi
        #           volumeMounts:
        #           - name: timezone-configuration
        #             mountPath: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME
  namespace: NAMESPACE
  labels:
    run: SERVICENAME
spec:
  type: NodePort
  ports:
    - name: PORTNAME
      port: PORT
      protocol: TCP
      nodePort: NODEPORT
  selector:
    app: APP